import type { CourseConfig } from '../types';

export const courses: CourseConfig[] = [
  {
    id: 'lake-jovita-north',
    name: 'Lake Jovita North',
    tees: [
      {
        id: 'ljn-gold',
        name: 'Gold',
        rating: 74.8,
        slope: 137,
        yardage: 7226,
        holes: [
          { hole: 1,  par: 5, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 13, yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 13, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 16, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 2,  yardage: 0 },
        ],
      },
      {
        id: 'ljn-blue',
        name: 'Blue',
        rating: 72.3,
        slope: 132,
        yardage: 6707,
        holes: [
          { hole: 1,  par: 5, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 13, yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 13, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 16, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 2,  yardage: 0 },
        ],
      },
      {
        id: 'ljn-green',
        name: 'Green',
        rating: 69.9,
        slope: 127,
        yardage: 6198,
        holes: [
          { hole: 1,  par: 5, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 13, yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 13, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 16, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 2,  yardage: 0 },
        ],
      },
      {
        id: 'ljn-white',
        name: 'White',
        rating: 67.7,
        slope: 118,
        yardage: 5744,
        holes: [
          { hole: 1,  par: 5, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 13, yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 13, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 16, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 2,  yardage: 0 },
        ],
      },
      {
        id: 'ljn-red',
        name: 'Red',
        rating: 69.1,
        slope: 118,
        yardage: 5084,
        holes: [
          { hole: 1,  par: 5, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 13, yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 13, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 16, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 2,  yardage: 0 },
        ],
      },
    ],
  },
  {
    id: 'lake-jovita-south',
    name: 'Lake Jovita South',
    tees: [
      {
        id: 'ljs-gold',
        name: 'Gold',
        rating: 74.5,
        slope: 139,
        yardage: 7153,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 9,  par: 5, strokeIndex: 15, yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 12, yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 5, strokeIndex: 2,  yardage: 0 },
          { hole: 14, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 6,  yardage: 0 },
        ],
      },
      {
        id: 'ljs-blue',
        name: 'Blue',
        rating: 71.8,
        slope: 133,
        yardage: 6612,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 9,  par: 5, strokeIndex: 15, yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 12, yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 5, strokeIndex: 2,  yardage: 0 },
          { hole: 14, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 6,  yardage: 0 },
        ],
      },
      {
        id: 'ljs-green',
        name: 'Green',
        rating: 69.8,
        slope: 128,
        yardage: 6192,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 9,  par: 5, strokeIndex: 15, yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 12, yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 5, strokeIndex: 2,  yardage: 0 },
          { hole: 14, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 6,  yardage: 0 },
        ],
      },
      {
        id: 'ljs-white',
        name: 'White',
        rating: 67.4,
        slope: 117,
        yardage: 5666,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 9,  par: 5, strokeIndex: 15, yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 12, yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 5, strokeIndex: 2,  yardage: 0 },
          { hole: 14, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 6,  yardage: 0 },
        ],
      },
      {
        id: 'ljs-red',
        name: 'Red',
        rating: 70.0,
        slope: 123,
        yardage: 5145,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 4,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 9,  par: 5, strokeIndex: 15, yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 12, yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 5, strokeIndex: 2,  yardage: 0 },
          { hole: 14, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 4,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 6,  yardage: 0 },
        ],
      },
    ],
  },
  {
    id: 'crescent-oaks',
    name: 'Crescent Oaks',
    tees: [
      {
        id: 'co-black',
        name: 'Black',
        rating: 72.7,
        slope: 134,
        yardage: 6763,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 3, strokeIndex: 11, yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'co-blue',
        name: 'Blue',
        rating: 70.1,
        slope: 128,
        yardage: 6258,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 3, strokeIndex: 11, yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'co-white',
        name: 'White',
        rating: 67.8,
        slope: 118,
        yardage: 5725,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 3, strokeIndex: 11, yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'co-red',
        name: 'Red',
        rating: 69.1,
        slope: 121,
        yardage: 5016,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 3, strokeIndex: 11, yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'co-orange',
        name: 'Orange',
        rating: 64.9,
        slope: 104,
        yardage: 4260,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 2,  par: 5, strokeIndex: 7,  yardage: 0 },
          { hole: 3,  par: 3, strokeIndex: 11, yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 5, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 9,  yardage: 0 },
          { hole: 10, par: 5, strokeIndex: 8,  yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 14, yardage: 0 },
          { hole: 12, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 18, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 6,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
    ],
  },
  {
    id: 'tpc-tampa-bay',
    name: 'TPC Tampa Bay',
    tees: [
      {
        id: 'tpc-black',
        name: 'Black',
        rating: 73.6,
        slope: 137,
        yardage: 6898,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 7,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 12, par: 5, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 14, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 12, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'tpc-blue',
        name: 'Blue',
        rating: 72.3,
        slope: 132,
        yardage: 6610,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 7,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 12, par: 5, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 14, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 12, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'tpc-white',
        name: 'White',
        rating: 69.7,
        slope: 126,
        yardage: 6056,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 7,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 12, par: 5, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 14, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 12, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'tpc-silver',
        name: 'Silver',
        rating: 67.4,
        slope: 121,
        yardage: 5550,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 7,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 12, par: 5, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 14, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 12, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'tpc-copper',
        name: 'Copper',
        rating: 68.7,
        slope: 121,
        yardage: 4990,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 2,  par: 3, strokeIndex: 13, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 4,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 5,  par: 4, strokeIndex: 15, yardage: 0 },
          { hole: 6,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 7,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 8,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 10, yardage: 0 },
          { hole: 11, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 12, par: 5, strokeIndex: 14, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 16, yardage: 0 },
          { hole: 14, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 15, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 16, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 17, par: 3, strokeIndex: 12, yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
    ],
  },
  {
    id: 'fox-hollow',
    name: 'Fox Hollow',
    tees: [
      {
        id: 'fh-black',
        name: 'Black',
        rating: 74.6,
        slope: 134,
        yardage: 7079,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 2,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 5,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 8,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 14, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'fh-blue',
        name: 'Blue',
        rating: 72.8,
        slope: 130,
        yardage: 6757,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 2,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 5,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 8,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 14, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'fh-white',
        name: 'White',
        rating: 71.2,
        slope: 125,
        yardage: 6288,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 2,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 5,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 8,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 14, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'fh-gold',
        name: 'Gold',
        rating: 68.3,
        slope: 122,
        yardage: 5908,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 2,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 5,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 8,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 14, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'fh-silver',
        name: 'Silver',
        rating: 66.9,
        slope: 125,
        yardage: 5529,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 2,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 5,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 8,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 14, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
      {
        id: 'fh-red',
        name: 'Red',
        rating: 70.9,
        slope: 125,
        yardage: 4825,
        holes: [
          { hole: 1,  par: 4, strokeIndex: 13, yardage: 0 },
          { hole: 2,  par: 4, strokeIndex: 11, yardage: 0 },
          { hole: 3,  par: 4, strokeIndex: 1,  yardage: 0 },
          { hole: 4,  par: 5, strokeIndex: 9,  yardage: 0 },
          { hole: 5,  par: 3, strokeIndex: 17, yardage: 0 },
          { hole: 6,  par: 4, strokeIndex: 5,  yardage: 0 },
          { hole: 7,  par: 4, strokeIndex: 3,  yardage: 0 },
          { hole: 8,  par: 3, strokeIndex: 15, yardage: 0 },
          { hole: 9,  par: 4, strokeIndex: 7,  yardage: 0 },
          { hole: 10, par: 4, strokeIndex: 14, yardage: 0 },
          { hole: 11, par: 5, strokeIndex: 6,  yardage: 0 },
          { hole: 12, par: 3, strokeIndex: 16, yardage: 0 },
          { hole: 13, par: 4, strokeIndex: 12, yardage: 0 },
          { hole: 14, par: 4, strokeIndex: 2,  yardage: 0 },
          { hole: 15, par: 5, strokeIndex: 10, yardage: 0 },
          { hole: 16, par: 3, strokeIndex: 18, yardage: 0 },
          { hole: 17, par: 4, strokeIndex: 8,  yardage: 0 },
          { hole: 18, par: 4, strokeIndex: 4,  yardage: 0 },
        ],
      },
    ],
  },
];

export const getCourse = (id: string): CourseConfig | undefined =>
  courses.find((c) => c.id === id);

export const getTee = (courseId: string, teeId: string) => {
  const course = getCourse(courseId);
  return course?.tees.find((t) => t.id === teeId);
};
